module.exports = {
    'VALIDATE_PHONE_FLAG': 10,
    'LOGIN_PHONE_FLAG': 20,
    'CHANGE_PASSWORD_LOGIN_FLAG':30,
    'CHANGE_PASSWORD_NO_LOGIN_FLAG':40,
    'REGISTER_TEMPL_ID' : '94257',
    'LOGIN_TEMPL_ID': '97082',
    'RESET_PASSWORD_TEMPL_ID' : '94261'
}